generator: admingenerator.generator.doctrine
params:
    model: Pokupo\LandingBundle\Entity\Content
    namespace_prefix: Pokupo
    concurrency_lock: ~
    bundle_name: LandingBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Контент
            display: [ title, alias, is_active ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: [ title, alias, is_active ]
    new:
        params:
            title: New object for LandingBundle
            tabs:
                Base: 
                    Base: [ title, alias, anons, content, is_active ]
                Meta:
                    Meta: [ meta ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Content.title }|"
            tabs:
                Base: 
                    Base: [ title, alias, anons, content, is_active ]
                Meta:
                    Meta: [ meta ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Content.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
