<?php

namespace Pokupo\LandingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentMetaRepository extends EntityRepository
{
}
