<?php

namespace Pokupo\LandingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    public function getListContents(){
        $q = $this->_em->createQueryBuilder();
        $query = $q->select("c")
                ->from("PokupoLandingBundle:Content", "c")
                ->addOrderBy('c.title');

        return $query;
    }
    
    public function GetContentByAlias($alias){
        $q = $this->_em->createQueryBuilder();
        $query = $q->select("c")
                ->from("PokupoLandingBundle:Content", "c")
                ->where('c.alias = :alias')
                ->andWhere('c.is_active = true')
                ->setParameter('alias', $alias)
                ->getQuery()
                ->getOneOrNullResult();

        return $query;
    }

    public function getSearchContent($search){
        $q = $this->_em->createQueryBuilder();
        $query = $q->select("c")
            ->from("PokupoLandingBundle:Content", "c")
            ->where('c.title LIKE :q')
            ->orWhere('c.content LIKE :q')
            ->andWhere('c.is_active = true')
            ->setParameter('q', '%'.$search.'%')
            ->getQuery()
            ->getResult();

        return $query;
    }
}
